# Generated by Django 3.1.7 on 2021-07-18 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_product',
            name='date_added',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='add_product',
            name='price',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='add_product',
            name='product_images',
            field=models.ImageField(upload_to='seller/images'),
        ),
    ]
