# Generated by Django 3.1.7 on 2021-07-18 14:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0008_auto_20210718_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_product',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 18, 19, 58, 44, 711013)),
        ),
        migrations.AlterField(
            model_name='add_product',
            name='product_images',
            field=models.ImageField(upload_to=''),
        ),
    ]
