# Generated by Django 3.1.7 on 2021-07-19 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0011_auto_20210719_0621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_product',
            name='date_added',
        ),
    ]
