# Generated by Django 3.1.7 on 2021-07-19 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0012_remove_add_product_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_product',
            name='current_Price',
            field=models.IntegerField(default=None),
        ),
    ]
