# Generated by Django 3.1.7 on 2021-07-19 01:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0014_add_product_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_product',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 19, 7, 29, 53, 425697)),
        ),
        migrations.AddField(
            model_name='add_product',
            name='item_id',
            field=models.CharField(default='K|c843ANc~', max_length=255),
        ),
    ]
