# Generated by Django 3.1.7 on 2021-07-19 04:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0015_auto_20210719_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_product',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 19, 9, 32, 31, 466000)),
        ),
        migrations.AlterField(
            model_name='add_product',
            name='item_id',
            field=models.CharField(default='>ZyC7w(<n<', max_length=255),
        ),
        migrations.AlterField(
            model_name='add_product',
            name='product_images',
            field=models.ImageField(upload_to=''),
        ),
    ]
