# Generated by Django 3.1.7 on 2021-07-19 04:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0017_auto_20210719_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_product',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 19, 9, 58, 18, 695853)),
        ),
        migrations.AlterField(
            model_name='add_product',
            name='item_id',
            field=models.CharField(default='3kq~zSF6:m', max_length=255),
        ),
    ]
