# Generated by Django 3.1.7 on 2021-07-19 04:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0018_auto_20210719_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_product',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 19, 9, 59, 20, 773937)),
        ),
        migrations.AlterField(
            model_name='add_product',
            name='item_id',
            field=models.CharField(default='.NK)Sfgk1@', max_length=255),
        ),
        migrations.AlterField(
            model_name='add_product',
            name='product_images',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
