# Generated by Django 3.1.7 on 2021-07-19 04:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0020_auto_20210719_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_product',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 19, 10, 6, 44, 376243)),
        ),
        migrations.AlterField(
            model_name='add_product',
            name='item_id',
            field=models.CharField(default='MDF?5bg=d)', max_length=255),
        ),
        migrations.AlterField(
            model_name='add_product',
            name='product_images',
            field=models.ImageField(upload_to=''),
        ),
    ]
