# Generated by Django 3.1.7 on 2021-07-19 05:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0029_auto_20210719_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_product',
            name='product_images',
        ),
        migrations.AlterField(
            model_name='add_product',
            name='current_Price',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='add_product',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 19, 11, 23, 13, 881997)),
        ),
        migrations.AlterField(
            model_name='add_product',
            name='item_id',
            field=models.CharField(default='v$|(x3TJOh', max_length=255),
        ),
    ]
