# Generated by Django 3.1.7 on 2021-07-19 05:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0030_auto_20210719_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_product',
            name='product_images',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='add_product',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 19, 11, 28, 5, 548358)),
        ),
        migrations.AlterField(
            model_name='add_product',
            name='item_id',
            field=models.CharField(default='qtNvkVJ@4V', max_length=255),
        ),
    ]
